spring:
  application:
    name: seckill-demo
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.126.128
      port: 6379
      password: 123456
      timeout: 5000ms
  rabbitmq:
    host: 192.168.126.128
    port: 5672
    username: admin
    password: admin123


#mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


